### ISSUE TITLE
Symbol Ada.Interrupts.Names.LTDC_Interrupt undefined

### ISSUE THREAD

**Issue by rveenker** [lambourg/Ada_Bare_Metal_Demos#1]
Hello,
When trying to build the balls example for my stm32f429 discovery board, I noticed that the LTDC_Interrupt symbol is missing (called from stm32.Ltdc). This is because the runtime from the GNAT GPL compiler is used instead of the Ada_Drivers_Library.
I found that the value should be 90, as defined in the Ada_Drivers_Library runtime.
The package Ada.Interrupts.Names for the stm32f429 names this interrupt 'LCD_TFT_Interrupt'.
Should these names perhaps be the same for all boards/runtimes?

**Comment by lambourg** [comment]
Hi Rob,

You should use the runtimes-library project to install more up-to-date runtimes for your compiler. Those rts fix a lot of glitches such as the one you mention.

To install the runtimes, checkout the project, run make install, and you should be ok. Tell me it not !

**Comment by rveenker** [comment]
Just installed the embedded-runtimes library and indeed the LTDC_Interrupts problem has gone.
Thanks!

But unlike the Certyflie and examples from the Ada_Drivers_Library project, I cannot debug any example from the Ada_Bare_Metal_Demos project.
I can build an example and the debugger starts, but when I 'continue' I get a 'Program received signal SIGTRAP, Trace/breakpoint trap  0x080191b9 in _start_rom ()'
Any ideas?

**Comment by lambourg** [comment]
Not really. Have you tried to put a breakpoint in your main program, and only then do a continue?
Here's the steps I usually take:
- perform a load to make sure the executable is flashed
- (gdb) monitor jtag_reset # make sure to fully reset the board
- (gdb) break file.adb:1234
- (gdb) continue

**Comment by rveenker** [comment]
Just found that when I include the line 'for Target use "arm-eabi" in the project file, the problem goes away!

**Comment by lambourg** [comment]
ok, good! So I'll close this issue, as as far as I know, all projects there define the target...

**Comment by rveenker** [comment]
Well, the target is defined in the common project, but not in the 'root' project.
The line: 'for Target use...' must be in the first project that you open apparently.
