### ISSUE TITLE
all_demos.gpr and GPS2016/2017 issues

### ISSUE THREAD

**Issue by ghost** [lambourg/Ada_Bare_Metal_Demos#3]
Hi all,
I am trying to run the examples from the repo with no success.

Specs:
  * Linux Fedora 25,
  * st-link from: https://github.com/texane/stlink
  * bash, verified st-util is in my $PATH

Issue with GPS 2016:
  1. Install gps2016 arm-eabi hosted on linux
  2. Clone embedded-runtimes and do python ./install.py
  3. Open all_demos.gpr
  4. gpr outputs the following message (and no projects are visible):
> [2017-06-27 13:34:38] /opt/gnat/gnat-arm-eabi/share/doc/gprbuild/html/gps_index.xml:1:0: No root element specified
> Welcome to GPS 2016 (20160515) hosted on i686-pc-linux-gnu
> the GNAT Programming Studio
> (c) 2001-2016 AdaCore
>
> [2017-06-27 13:34:48] /home/user/Ada_Bare_Metal_Demos/common/common.gpr:23:11: undefined attribute "connection_tool"
> Auto-VCS: using Git

Issue with GPS 2017:
  1. Install gps2017 arm-eabi hosted on linux
  2. Clone embedded-runtimes and do python ./install.py
     - Compilation fails, but I compile with gps2016 and just install them in the gps2017 all is fine
  3. Open all_demos.gpr
  4. gpr outputs the following message (but I can see the projects on the left):
> Project
>     /home/user/work/projects/ada/Ada_Bare_Metal_Demos/balls/balls_stm32f429disco.gpr
>         7:23 warning: object directory "obj/stm32f429disco" not found

**Comment by lambourg** [comment]
Hi,

That's expected: the project files have to be used with GPL 2017 (GPS + compiler). The object directories are not in the repository, so you need to either configure GPS to do it for you (open the 'build targets' properties from menu Build->Targets, for target "Build Main" and "Build All" check the box "Create object dirs"), or if building manually with gprbuild, use the switch "-p" that automatically creates the missing object directories.

Best regards,
- Jerome

**Comment by ghost** [comment]
Thank you, everything is building correctly! :)
